/**
 * "Entretenimiento": los juegos sueltos de las mesitas (/hoy/jugar). Todo vive en el teléfono;
 * el premio se gana completando los cuatro con marcas difíciles a propósito.
 */

export type TriviaItem = { text: string; answer: boolean; why: string };

/** Verdadero o falso de barra y cocina. Cada partida toma 8 al azar. */
export const TRIVIA: TriviaItem[] = [
  { text: "El Negroni nació en Florencia, cuando un conde pidió su Americano con gin en vez de soda.", answer: true, why: "Camillo Negroni, en el Caffè Casoni, alrededor de 1919." },
  { text: "La tónica lleva quinina, que se tomaba contra la malaria; el gin se sumó para que bajara mejor.", answer: true, why: "Los oficiales británicos en India la mezclaban con gin, azúcar y lima." },
  { text: "El vermut se llama así por el ajenjo: “Wermut” es ajenjo en alemán.", answer: true, why: "Un vino aromatizado con hierbas, y el ajenjo era la principal." },
  { text: "El Mojito es un cóctel de origen mexicano.", answer: false, why: "Es cubano: ron, lima, menta, azúcar y soda." },
  { text: "El fernet con coca se popularizó en Córdoba y Argentina toma la mayor parte del Fernet Branca del mundo.", answer: true, why: "Cerca de tres cuartos de la producción mundial se toma en Argentina." },
  { text: "La caipirinha se prepara con ron blanco.", answer: false, why: "Se hace con cachaça, destilado de caña brasileño." },
  { text: "El Aperol se creó en Padua, Italia, en 1919.", answer: true, why: "Los hermanos Barbieri lo presentaron en la feria de Padua." },
  { text: "Un “sour” lleva siempre destilado, cítrico y algo dulce.", answer: true, why: "Esa es la fórmula de la familia: whisky sour, pisco sour, amaretto sour…" },
  { text: "El Dry Martini clásico se prepara con vodka.", answer: false, why: "El clásico es gin y vermut seco; con vodka se llama Vodka Martini." },
  { text: "El hielo grande enfría igual pero diluye menos que el hielo chico.", answer: true, why: "Menos superficie por volumen: se derrite más lento." },
  { text: "Los arancini son sicilianos y su nombre quiere decir “naranjitas”, por la forma.", answer: true, why: "Bolas de arroz fritas, doradas y redondas como una naranja chica." },
  { text: "La bondiola es un corte de la pierna del cerdo.", answer: false, why: "Es del cuello. Por eso es tan jugosa braseada." },
  { text: "El pimentón ahumado se seca con humo de leña de roble o encina.", answer: true, why: "Así se hace el de La Vera, en Extremadura." },
  { text: "El Old Fashioned se llama así porque es un cóctel “a la vieja manera”: destilado, azúcar, bitter y agua.", answer: true, why: "Es la definición original de cóctel, de principios del 1800." },
  { text: "El Aperol Spritz se inventó en Buenos Aires.", answer: false, why: "Es del norte de Italia; el spritz viene de los soldados austríacos que “rociaban” el vino con agua." },
  { text: "El gin se destila a partir de uva.", answer: false, why: "Es un destilado neutro (casi siempre de cereal) aromatizado con enebro." },
  { text: "El pisco es un destilado de uva.", answer: true, why: "Aguardiente de uva de Perú y Chile; de ahí el pisco sour." },
  { text: "El tequila se hace con cactus.", answer: false, why: "Se hace con agave azul, que es una planta parecida al aloe, no un cactus." },
  { text: "El mezcal se puede hacer con varias clases de agave.", answer: true, why: "Por eso hay tantos estilos; el tequila, en cambio, solo con agave azul." },
  { text: "El Cynar es un amaro a base de alcaucil.", answer: true, why: "Lo dice hasta la etiqueta: Cynara scolymus." },
  { text: "El Campari es rojo por la remolacha.", answer: false, why: "Históricamente era la cochinilla; hoy es colorante. La remolacha no." },
  { text: "El Aperol tiene menos alcohol que el Campari.", answer: true, why: "Alrededor de 11 % contra unos 25 %." },
  { text: "Un “highball” es un trago largo con hielo, destilado y una bebida con gas.", answer: true, why: "Gin tonic, fernet con coca y whisky con soda son highballs." },
  { text: "Agitar en coctelera enfría más y airea el trago que revolver.", answer: true, why: "Por eso lo que lleva cítrico o clara se bate, y lo que es solo alcohol (Negroni, Martini) se revuelve." },
  { text: "El Negroni se bate en coctelera.", answer: false, why: "Se revuelve: los tragos solo de alcohol se revuelven para que queden sedosos, no turbios." },
  { text: "El bitter Angostura es de Trinidad y Tobago.", answer: true, why: "Se hace ahí desde 1875, aunque nació en la ciudad de Angostura, hoy Venezuela." },
  { text: "El vermut rojo es rojo por el vino tinto.", answer: false, why: "Se hace con vino blanco; el color viene del caramelo y las hierbas." },
  { text: "El Manhattan lleva whisky, vermut rojo y bitter.", answer: true, why: "Es el primo del Negroni pero con whisky, de fines del 1800 en Nueva York." },
  { text: "La Caipirinha es el cóctel nacional de Brasil.", answer: true, why: "Cachaça, lima y azúcar. Con vodka se llama caipiroska." },
  { text: "El Daiquiri original lleva frutilla y se hace frozen.", answer: false, why: "El original es ron, lima y azúcar, batido y colado. Lo frozen vino después." },
  { text: "El “sour” de clara de huevo se bate primero sin hielo.", answer: true, why: "Es el “dry shake”: sin hielo se forma la espuma, después se enfría." },
  { text: "El fernet es un amaro: una bebida amarga de hierbas.", answer: true, why: "Mirra, ruibarbo, manzanilla, azafrán… y mucho amargo." },
  { text: "Las burbujas del champagne vienen de agregarle gas.", answer: false, why: "Vienen de una segunda fermentación dentro de la botella." },
  { text: "El vino se sirve más frío cuanto más ligero es.", answer: true, why: "Blancos y espumantes bien fríos; tintos con cuerpo apenas frescos." },
  { text: "El Malbec es una uva de origen francés.", answer: true, why: "De Cahors, en el sudoeste de Francia; Argentina la hizo famosa." },
  { text: "Los langostinos cambian de color al cocinarse.", answer: true, why: "De gris a rosado: el calor libera un pigmento que estaba escondido." },
  { text: "Brasear es cocinar rápido a fuego muy fuerte.", answer: false, why: "Es lo contrario: dorar y después cocinar largo y tapado con líquido." },
  { text: "La salsa passata es tomate triturado y colado, sin cocinar demasiado.", answer: true, why: "Por eso queda fresca y lisa, distinta a una salsa reducida." },
  { text: "El aceto balsámico tradicional se envejece en barricas durante años.", answer: true, why: "El de Módena tradicional, al menos doce años." },
  { text: "La pimienta negra y la blanca vienen de plantas distintas.", answer: false, why: "Son el mismo fruto: la negra se seca con cáscara, la blanca sin ella." },
  { text: "El umami es uno de los cinco sabores básicos.", answer: true, why: "Dulce, salado, ácido, amargo y umami (el “sabroso” del queso, el tomate, la carne)." },
  { text: "El cardamomo es una semilla de la familia del jengibre.", answer: true, why: "Y una de las especias más caras del mundo." },
  { text: "Flambear quema todo el alcohol del plato.", answer: false, why: "Queda una parte; lo que se busca es el aroma y el espectáculo." },
  { text: "Los arancini se rellenan a veces con ragú y queso.", answer: true, why: "El clásico siciliano: arroz, ragú, arvejas y queso, fritos." },
  { text: "La cebolla hace llorar por un gas que suelta al cortarla.", answer: true, why: "Se forma al romper sus células; el cuchillo bien afilado ayuda." },
  { text: "La tortilla de papas nació en Italia.", answer: false, why: "Es española; la versión italiana con verduras se llama frittata." },
  { text: "El primer libro de cócteles se publicó en 1862.", answer: true, why: "“How to Mix Drinks”, de Jerry Thomas, el primer bartender famoso." },
  { text: "El hielo en un cóctel es solo para enfriar; no cambia el sabor.", answer: false, why: "También diluye: un poco de agua abre los aromas y suaviza el alcohol." },
  { text: "Salar el borde de la copa se hace pasando lima y luego sal.", answer: true, why: "La lima moja el borde y la sal se pega; como en la Margarita." },
];

/** Consignas de mímica para la mesa. Se suman los platos y tragos de la noche. */
export const MIMICA_BASE = [
  "Batir un cóctel en la coctelera",
  "Pelar un langostino",
  "Quemarse con la sartén",
  "Probar algo muy picante",
  "Abrir un champagne",
  "Un bartender haciendo malabares",
  "Un sommelier catando vino",
  "Comer espagueti sin hacer ruido",
  "Exprimir un limón y que te salte al ojo",
  "Flambear y asustarse",
  "Amasar pizza",
  "Cortar cebolla y llorar",
  "Un mozo con la bandeja llena",
  "Un brindis eterno",
  "Tomar un fernet demasiado fuerte",
  "Hacer un asado con humo",
  "Un pulpo",
  "Ordeñar una vaca",
  "Servir vino y que se derrame",
  "Buscar el sacacorchos que no aparece",
  "Un chef gritando en la cocina",
  "Rallar queso hasta el nudillo",
  "Chuparse los dedos",
  "Una gallina poniendo un huevo",
];
